### ISSUE TITLE
Feature Request - Style of In-Text Citations

### ISSUE THREAD

**Issue by pointyegg** [mabentwickeltsich/MendeleyMacros#5]
I don't know if I implemented the VBA code incorrectly or if this is intentional but my in-text IEEE citations appear blue with an underline (default hyperlink). I would like them to remain black with no underline. Would it be possible to have an option for this?

**Comment by mabentwickeltsich** [comment]
Hi @pointyegg,

That is the normal behavior of Microsoft Word when you create hyperlinks, they will take the corresponding Microsoft Word style. It would be impractical to add this as a feature because of the amount of different styles people may want to use.

If you need a different style for the hyperlinks, you have to modify the Microsoft Word style to fit your needs. Have a look at [Hyperlink Formatting](https://wordribbon.tips.net/T010249_Hyperlink_Formatting.html) where it is explained step by step. Once you modify the style, remove the hyperlinks and create them again to update their style.

Cheers
Luis

**Comment by pointyegg** [comment]
Thanks for the tip! Thanks also for sharing these macros. I've never had to delve into Word settings much before (also putting together a dissertation).
