### ISSUE TITLE
Executing macros

### ISSUE THREAD

**Issue by DennyValsamakis** [mabentwickeltsich/MendeleyMacros#8]
Hi Jose,

I am trying to use the macro that creates hyperlinks for the iEEE style. However I am being given the following error:
![image](https://user-images.githubusercontent.com/53864154/62622687-35d83f80-b91f-11e9-8962-455c5de11ca2.png)

I have enabled regular expressions 5.5, could you kindly provide some instructions as to how I can fix this?

**Comment by mabentwickeltsich** [comment]
Dear @DennyValsamakis,

The problem arises because of the missing[ _Microsoft VBScript Regular Expressions 5.5_](https://github.com/mabentwickeltsich/MendeleyMacros#gwdg_) as described in [ Issue #4. ](https://github.com/mabentwickeltsich/MendeleyMacros/issues/4#issuecomment-328130943)

Time ago, somebody pointed out that he “_[had] ticked the Regular Expression 5.5 option in VBA_”,  but somehow he was having the compile error. After verification, he found that this may be a _project-specific_ setting and the problem was solved by activating the regular expressions  in the document **AGAIN**.
Please, confirm that _Microsoft VBScript Regular Expressions 5.5_ is indeed activated in the document you want to execute the macros.

Follow the steps in this link if you have doubts:
[How to Use/Enable (RegExp object) Regular Expression using VBA (MACRO) in word](https://stackoverflow.com/questions/25102372/how-to-use-enable-regexp-object-regular-expression-using-vba-macro-in-word)

Cheers
Luis

**Comment by DennyValsamakis** [comment]
Hi @mabentwickeltsich,

I removed the macros, re-added them but this time enabled regular expressions prior to saving and closing Visual Basic Editor. It is now working perfectly. Thank you very much! This is the only place on the web I have found a solution remotely convenient, thanks for all the help!

Kind Regards
Denny
